/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OriginalsRouteImport } from './routes/originals'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R73778054DottxtRouteImport } from './routes/73778054[.]txt'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedMyTicketsRouteImport } from './routes/_authenticated/my-tickets'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedWatchSlugRouteImport } from './routes/_authenticated/watch.$slug'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTrialsRouteImport } from './routes/_authenticated/admin/trials'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin/revenue'
import { Route as AuthenticatedAdminRegenThumbnailsRouteImport } from './routes/_authenticated/admin/regen-thumbnails'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminNotifyListRouteImport } from './routes/_authenticated/admin/notify-list'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin/memberships'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminFooterRouteImport } from './routes/_authenticated/admin/footer'
import { Route as AuthenticatedAdminFilmsRouteImport } from './routes/_authenticated/admin/films'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin/faq'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminContributionsRouteImport } from './routes/_authenticated/admin/contributions'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBannerRouteImport } from './routes/_authenticated/admin/banner'
import { Route as AuthenticatedAdminAppearanceRouteImport } from './routes/_authenticated/admin/appearance'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPerfHeroRouteImport } from './routes/api/public/perf/hero'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicIrPaymentsCallbackRouteImport } from './routes/api/public/ir-payments/callback'
import { Route as ApiPublicHooksTrialRemindersRouteImport } from './routes/api/public/hooks/trial-reminders'
import { Route as AuthenticatedAdminFilmsFilmIdCreditsRouteImport } from './routes/_authenticated/admin/films.$filmId.credits'
import { Route as AuthenticatedAdminFilmsFilmIdAnalyticsRouteImport } from './routes/_authenticated/admin/films.$filmId.analytics'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsRoute = OriginalsRouteImport.update({
  id: '/originals',
  path: '/originals',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R73778054DottxtRoute = R73778054DottxtRouteImport.update({
  id: '/73778054.txt',
  path: '/73778054.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyTicketsRoute = AuthenticatedMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchSlugRoute = AuthenticatedWatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTrialsRoute =
  AuthenticatedAdminTrialsRouteImport.update({
    id: '/trials',
    path: '/trials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegenThumbnailsRoute =
  AuthenticatedAdminRegenThumbnailsRouteImport.update({
    id: '/regen-thumbnails',
    path: '/regen-thumbnails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNotifyListRoute =
  AuthenticatedAdminNotifyListRouteImport.update({
    id: '/notify-list',
    path: '/notify-list',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFooterRoute =
  AuthenticatedAdminFooterRouteImport.update({
    id: '/footer',
    path: '/footer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFilmsRoute = AuthenticatedAdminFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContributionsRoute =
  AuthenticatedAdminContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannerRoute =
  AuthenticatedAdminBannerRouteImport.update({
    id: '/banner',
    path: '/banner',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAppearanceRoute =
  AuthenticatedAdminAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPerfHeroRoute = ApiPublicPerfHeroRouteImport.update({
  id: '/api/public/perf/hero',
  path: '/api/public/perf/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIrPaymentsCallbackRoute =
  ApiPublicIrPaymentsCallbackRouteImport.update({
    id: '/api/public/ir-payments/callback',
    path: '/api/public/ir-payments/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialRemindersRoute =
  ApiPublicHooksTrialRemindersRouteImport.update({
    id: '/api/public/hooks/trial-reminders',
    path: '/api/public/hooks/trial-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminFilmsFilmIdCreditsRoute =
  AuthenticatedAdminFilmsFilmIdCreditsRouteImport.update({
    id: '/$filmId/credits',
    path: '/$filmId/credits',
    getParentRoute: () => AuthenticatedAdminFilmsRoute,
  } as any)
const AuthenticatedAdminFilmsFilmIdAnalyticsRoute =
  AuthenticatedAdminFilmsFilmIdAnalyticsRouteImport.update({
    id: '/$filmId/analytics',
    path: '/$filmId/analytics',
    getParentRoute: () => AuthenticatedAdminFilmsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/73778054.txt': typeof R73778054DottxtRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/membership': typeof MembershipRoute
  '/not-found': typeof NotFoundRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contributions': typeof AuthenticatedAdminContributionsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/films': typeof AuthenticatedAdminFilmsRouteWithChildren
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/notify-list': typeof AuthenticatedAdminNotifyListRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/regen-thumbnails': typeof AuthenticatedAdminRegenThumbnailsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/trials': typeof AuthenticatedAdminTrialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/watch/$slug': typeof AuthenticatedWatchSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/ir-payments/callback': typeof ApiPublicIrPaymentsCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/perf/hero': typeof ApiPublicPerfHeroRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/films/$filmId/analytics': typeof AuthenticatedAdminFilmsFilmIdAnalyticsRoute
  '/admin/films/$filmId/credits': typeof AuthenticatedAdminFilmsFilmIdCreditsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/73778054.txt': typeof R73778054DottxtRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/membership': typeof MembershipRoute
  '/not-found': typeof NotFoundRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contributions': typeof AuthenticatedAdminContributionsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/films': typeof AuthenticatedAdminFilmsRouteWithChildren
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/notify-list': typeof AuthenticatedAdminNotifyListRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/regen-thumbnails': typeof AuthenticatedAdminRegenThumbnailsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/trials': typeof AuthenticatedAdminTrialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/watch/$slug': typeof AuthenticatedWatchSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/ir-payments/callback': typeof ApiPublicIrPaymentsCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/perf/hero': typeof ApiPublicPerfHeroRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/films/$filmId/analytics': typeof AuthenticatedAdminFilmsFilmIdAnalyticsRoute
  '/admin/films/$filmId/credits': typeof AuthenticatedAdminFilmsFilmIdCreditsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/73778054.txt': typeof R73778054DottxtRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/membership': typeof MembershipRoute
  '/not-found': typeof NotFoundRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/_authenticated/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/contributions': typeof AuthenticatedAdminContributionsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/films': typeof AuthenticatedAdminFilmsRouteWithChildren
  '/_authenticated/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/notify-list': typeof AuthenticatedAdminNotifyListRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/regen-thumbnails': typeof AuthenticatedAdminRegenThumbnailsRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/trials': typeof AuthenticatedAdminTrialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/watch/$slug': typeof AuthenticatedWatchSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/ir-payments/callback': typeof ApiPublicIrPaymentsCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/perf/hero': typeof ApiPublicPerfHeroRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/films/$filmId/analytics': typeof AuthenticatedAdminFilmsFilmIdAnalyticsRoute
  '/_authenticated/admin/films/$filmId/credits': typeof AuthenticatedAdminFilmsFilmIdCreditsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/73778054.txt'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/membership'
    | '/not-found'
    | '/originals'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/account'
    | '/library'
    | '/my-tickets'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/films/$slug'
    | '/admin/analytics'
    | '/admin/appearance'
    | '/admin/banner'
    | '/admin/categories'
    | '/admin/contributions'
    | '/admin/coupons'
    | '/admin/faq'
    | '/admin/films'
    | '/admin/footer'
    | '/admin/homepage'
    | '/admin/memberships'
    | '/admin/menu'
    | '/admin/notify-list'
    | '/admin/pages'
    | '/admin/regen-thumbnails'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tickets'
    | '/admin/trials'
    | '/admin/users'
    | '/watch/$slug'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/ir-payments/callback'
    | '/api/public/payments/webhook'
    | '/api/public/perf/hero'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/films/$filmId/analytics'
    | '/admin/films/$filmId/credits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/73778054.txt'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/membership'
    | '/not-found'
    | '/originals'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/account'
    | '/library'
    | '/my-tickets'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/films/$slug'
    | '/admin/analytics'
    | '/admin/appearance'
    | '/admin/banner'
    | '/admin/categories'
    | '/admin/contributions'
    | '/admin/coupons'
    | '/admin/faq'
    | '/admin/films'
    | '/admin/footer'
    | '/admin/homepage'
    | '/admin/memberships'
    | '/admin/menu'
    | '/admin/notify-list'
    | '/admin/pages'
    | '/admin/regen-thumbnails'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tickets'
    | '/admin/trials'
    | '/admin/users'
    | '/watch/$slug'
    | '/lovable/email/suppression'
    | '/admin'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/ir-payments/callback'
    | '/api/public/payments/webhook'
    | '/api/public/perf/hero'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/films/$filmId/analytics'
    | '/admin/films/$filmId/credits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/73778054.txt'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/membership'
    | '/not-found'
    | '/originals'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/library'
    | '/_authenticated/my-tickets'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/films/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/appearance'
    | '/_authenticated/admin/banner'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/contributions'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/films'
    | '/_authenticated/admin/footer'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/memberships'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/notify-list'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/regen-thumbnails'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/trials'
    | '/_authenticated/admin/users'
    | '/_authenticated/watch/$slug'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/ir-payments/callback'
    | '/api/public/payments/webhook'
    | '/api/public/perf/hero'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/films/$filmId/analytics'
    | '/_authenticated/admin/films/$filmId/credits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R73778054DottxtRoute: typeof R73778054DottxtRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  MembershipRoute: typeof MembershipRoute
  NotFoundRoute: typeof NotFoundRoute
  OriginalsRoute: typeof OriginalsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksTrialRemindersRoute: typeof ApiPublicHooksTrialRemindersRoute
  ApiPublicIrPaymentsCallbackRoute: typeof ApiPublicIrPaymentsCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPerfHeroRoute: typeof ApiPublicPerfHeroRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals': {
      id: '/originals'
      path: '/originals'
      fullPath: '/originals'
      preLoaderRoute: typeof OriginalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/73778054.txt': {
      id: '/73778054.txt'
      path: '/73778054.txt'
      fullPath: '/73778054.txt'
      preLoaderRoute: typeof R73778054DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-tickets': {
      id: '/_authenticated/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedMyTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watch/$slug': {
      id: '/_authenticated/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof AuthenticatedWatchSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trials': {
      id: '/_authenticated/admin/trials'
      path: '/trials'
      fullPath: '/admin/trials'
      preLoaderRoute: typeof AuthenticatedAdminTrialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/regen-thumbnails': {
      id: '/_authenticated/admin/regen-thumbnails'
      path: '/regen-thumbnails'
      fullPath: '/admin/regen-thumbnails'
      preLoaderRoute: typeof AuthenticatedAdminRegenThumbnailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notify-list': {
      id: '/_authenticated/admin/notify-list'
      path: '/notify-list'
      fullPath: '/admin/notify-list'
      preLoaderRoute: typeof AuthenticatedAdminNotifyListRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/memberships': {
      id: '/_authenticated/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/footer': {
      id: '/_authenticated/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AuthenticatedAdminFooterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/films': {
      id: '/_authenticated/admin/films'
      path: '/films'
      fullPath: '/admin/films'
      preLoaderRoute: typeof AuthenticatedAdminFilmsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contributions': {
      id: '/_authenticated/admin/contributions'
      path: '/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AuthenticatedAdminContributionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banner': {
      id: '/_authenticated/admin/banner'
      path: '/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AuthenticatedAdminBannerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/appearance': {
      id: '/_authenticated/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AuthenticatedAdminAppearanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/perf/hero': {
      id: '/api/public/perf/hero'
      path: '/api/public/perf/hero'
      fullPath: '/api/public/perf/hero'
      preLoaderRoute: typeof ApiPublicPerfHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ir-payments/callback': {
      id: '/api/public/ir-payments/callback'
      path: '/api/public/ir-payments/callback'
      fullPath: '/api/public/ir-payments/callback'
      preLoaderRoute: typeof ApiPublicIrPaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-reminders': {
      id: '/api/public/hooks/trial-reminders'
      path: '/api/public/hooks/trial-reminders'
      fullPath: '/api/public/hooks/trial-reminders'
      preLoaderRoute: typeof ApiPublicHooksTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/films/$filmId/credits': {
      id: '/_authenticated/admin/films/$filmId/credits'
      path: '/$filmId/credits'
      fullPath: '/admin/films/$filmId/credits'
      preLoaderRoute: typeof AuthenticatedAdminFilmsFilmIdCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminFilmsRoute
    }
    '/_authenticated/admin/films/$filmId/analytics': {
      id: '/_authenticated/admin/films/$filmId/analytics'
      path: '/$filmId/analytics'
      fullPath: '/admin/films/$filmId/analytics'
      preLoaderRoute: typeof AuthenticatedAdminFilmsFilmIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminFilmsRoute
    }
  }
}

interface AuthenticatedAdminFilmsRouteChildren {
  AuthenticatedAdminFilmsFilmIdAnalyticsRoute: typeof AuthenticatedAdminFilmsFilmIdAnalyticsRoute
  AuthenticatedAdminFilmsFilmIdCreditsRoute: typeof AuthenticatedAdminFilmsFilmIdCreditsRoute
}

const AuthenticatedAdminFilmsRouteChildren: AuthenticatedAdminFilmsRouteChildren =
  {
    AuthenticatedAdminFilmsFilmIdAnalyticsRoute:
      AuthenticatedAdminFilmsFilmIdAnalyticsRoute,
    AuthenticatedAdminFilmsFilmIdCreditsRoute:
      AuthenticatedAdminFilmsFilmIdCreditsRoute,
  }

const AuthenticatedAdminFilmsRouteWithChildren =
  AuthenticatedAdminFilmsRoute._addFileChildren(
    AuthenticatedAdminFilmsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAppearanceRoute: typeof AuthenticatedAdminAppearanceRoute
  AuthenticatedAdminBannerRoute: typeof AuthenticatedAdminBannerRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminContributionsRoute: typeof AuthenticatedAdminContributionsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminFilmsRoute: typeof AuthenticatedAdminFilmsRouteWithChildren
  AuthenticatedAdminFooterRoute: typeof AuthenticatedAdminFooterRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminNotifyListRoute: typeof AuthenticatedAdminNotifyListRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminRegenThumbnailsRoute: typeof AuthenticatedAdminRegenThumbnailsRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTrialsRoute: typeof AuthenticatedAdminTrialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAppearanceRoute: AuthenticatedAdminAppearanceRoute,
    AuthenticatedAdminBannerRoute: AuthenticatedAdminBannerRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminContributionsRoute: AuthenticatedAdminContributionsRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
    AuthenticatedAdminFilmsRoute: AuthenticatedAdminFilmsRouteWithChildren,
    AuthenticatedAdminFooterRoute: AuthenticatedAdminFooterRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
    AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
    AuthenticatedAdminNotifyListRoute: AuthenticatedAdminNotifyListRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminRegenThumbnailsRoute:
      AuthenticatedAdminRegenThumbnailsRoute,
    AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminTrialsRoute: AuthenticatedAdminTrialsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMyTicketsRoute: typeof AuthenticatedMyTicketsRoute
  AuthenticatedWatchSlugRoute: typeof AuthenticatedWatchSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMyTicketsRoute: AuthenticatedMyTicketsRoute,
  AuthenticatedWatchSlugRoute: AuthenticatedWatchSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R73778054DottxtRoute: R73778054DottxtRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  MembershipRoute: MembershipRoute,
  NotFoundRoute: NotFoundRoute,
  OriginalsRoute: OriginalsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksTrialRemindersRoute: ApiPublicHooksTrialRemindersRoute,
  ApiPublicIrPaymentsCallbackRoute: ApiPublicIrPaymentsCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPerfHeroRoute: ApiPublicPerfHeroRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
